### ISSUE TITLE
Bridge port not opening - Plugin fails to load.

### ISSUE THREAD

**Issue by jsindy** [trezor/webwallet#16]
When I launch the webwallet with grunt server the plugin fails to load.

In the config we have https://localback.net:21324

21324 never opens on 127.0.0.1

Please advise. Is there a indepth log file I can look at?

Error from GUI

["error","Fri, 09 Jan 2015 07:15:55 GMT","[app] Loading http transport failed",{"crossDomain":true}]
["log","Fri, 09 Jan 2015 07:15:55 GMT","[trezor] Loaded plugin 1.0.5"]
["error","Fri, 09 Jan 2015 07:15:55 GMT",{}]

Thanks for your time, I am hoping to be able to help commit code.

**Comment by prusnak** [comment]
That's OK. 

Error (line 1) you see is webwallet reporting that it cannot find bridge, so it goes on trying loading plugin. Which succeeded (line 2).

Please reach our TREZOR support on support@bitcointrezor.com so they'll help you with debugging your issue (also report your operating system, browser version, etc).

**Comment by jpochyla** [comment]
I've clarified the workflow in 72c7421d48176a1fcf5f10b0e2adc00d07a91fc1
