### ISSUE TITLE
tag stable doesn't seem to load plugin

### ISSUE THREAD

**Issue by jsindy** [trezor/webwallet#18]
I assume stable tag is what is on running in production at mytrezor.com

~/webwallet/app$ python -m SimpleHTTPServer

Doesn't seem to load plugin successfully.

Trying to run current code on mytrezor.com locally, any help would be appreciated.

**Comment by prusnak** [comment]
See config mentioned in #17 for the whitelist.

Make sure you use https://localhost/ and not https://127.0.0.1/
